---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  run_list:
  - recipe[apt]

- name: debian-6.0.7
  run_list:
  - recipe[apt]

- name: fedora-20

suites:
- name: default
  run_list:
  - recipe[netatalk]
  attributes: {}
- name: build_deb
  run_list:
  - recipe[netatalk]
  attributes: { netatalk: { package_recipe: "build_deb" } }
- name: backport_deb
  run_list:
  - recipe[netatalk]
  attributes: { netatalk: { package_recipe: "backport_deb" } }
